### ISSUE TITLE
undefined method 'casecmp' NoMethodError

### ISSUE THREAD

**Issue by dpgaspar** [deep-security/chef#9]
Hi,

when running the new 1.1.1 version i get:

```
Error executing action `run` on resource 'execute[activate_ds_agent]'

   NoMethodError

undefined method `casecmp?' for "D0:68:DE:48:1B:DC:4D:00:89:07:7F:85:15:20:C5:90:11:EB:56:6A":String

```

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @dpgaspar ,
Thanks for using our chef cookbook.
We'll try to reproduce this issue in our end.
At the same time, could you provide some more information about your environment?
1. Which Chef client version did you used?
2. Which OS/version did you try to use the cookbook?
3. What Ruby version did you installed on the client?

**Comment by stevenswager** [comment]
Getting same error.

1. chef client version 12.21.12
2. Ubuntu 16.04
3. ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by DeepSecurityOpenSourceSupport** [comment]
Thanks @stevenswager , we'll try to reproduce it.
Hi @dpgaspar , could you also provide the versions you used? It would be better if we can verify both situation and compare the difference between our environment.

**Comment by stevenswager** [comment]
Issue seems to be around using ruby 2.3, works fine with ruby 2.4 and above.

**Comment by DeepSecurityOpenSourceSupport** [comment]
That will be great @stevenswager , will check if we should change it to the older function now.
Thanks

**Comment by DeepSecurityOpenSourceSupport** [comment]
The issue is fixed in PR #13, with new release version 1.1.2
Thanks @stevenswager & @dpgaspar , please let us know if you encounter any other issue.
